### ISSUE TITLE
Reports 411 (SignhostException: Response code: 411, message: Unknown error) on curl 7.64.1

### ISSUE THREAD

**Issue by jstolp** [steffjenl/laravel-signhost#10]
When starting a transaction to signhost, it reports a 411 error. I'm using the latest version (v1.3.6)

```
Signhost\\Exception\\SignhostException: Response code: 411, message: Unknown error\n at Signhost\\SignhostClient->assertSuccessfulResponse (SignhostClient.php:205)\n at Signhost\\SignhostClient->performCURLRequest (SignhostClient.php:173)\n at Signhost\\SignhostClient->performRequest (SignhostClient.php:101)\n at Signhost\\Signhost->startTransaction (Signhost.php:108)\n ...
```

**Comment by jstolp** [comment]
Might be related: https://github.com/Evidos/signhost-phpdemoclient/issues/16

**Comment by jstolp** [comment]
We'll need to add something like:

```
if (false !== strpos($endpoint, 'start')) {
                $headers[] = "Content-Length: 0";
     }
```

SignHost requires the content-length to be send for some reason.

**Comment by MrJoe** [comment]
Signhost does only require the content-length when the HTTP specs says so you should. When you do a Put (or Post) call with an Content-Type header you are indicating a body will be sent in which case the Content-Length is required.
If you are not going to sent a content body just leave the Content-Type header out and it will work without requiring a Content-Length header.

**Comment by jstolp** [comment]
@MrJoe  Thnx, i'll update it as suggested.
