### ISSUE TITLE
cURL version incompatible with the code...

### ISSUE THREAD

**Issue by jstolp** [steffjenl/laravel-signhost#13]
The story continues...

I've pinpointed the issue to a difference in the cURL library we are using.

does not work with v1.3.6 (411 error from signhost)
```
curl 7.67.0 (x86_64-redhat-linux-gnu) 
```
Curl 7.67.0 -> use v1.3.7

does not work with v1.3.7 (502 error from signhost)
```
curl 7.29.0 (x86_64-redhat-linux-gnu) 
```
Curl 7.29.0 -> use v1.3.6

I'll investigate further.

**Comment by talkinnl** [comment]
The request header logic + tricks in Signhost\SignhostClient needs to be cleaned up.

\Signhost\SignhostClient::__construct() :
Do not set a default Content-Type header.

\Signhost\SignhostClient::performRequest() : 
if a file is uploaded: add 'Content-Type: application/pdf'
elseif a request body is present 'Content-Type: application/json'
and no Content-Type for other requests (i.e. HEAD, GET and the PUT start which don't have a body)

Effective change:
- This will remove the Content-Type from the PUT start.
- This removes error prone unset/overwrite hacks.
- Not tested, but I really suspect this'll be better on all curl versions. ;)

**Comment by jstolp** [comment]
@talkinnl What do you think about this (generated) client?
 
https://github.com/jstolp/signhost/tree/master/php-client

we can integrate it into @steffjenl 's library

**Comment by steffjenl** [comment]
I have changed some code so we are compatible with the wishes from @Evidos.
v1.3.8 is now releases, @jstolp can you test is version?

* only when $data is set and has data and valid json data we are setting the Content-Type: application/json header and the Content-Length header
* only when we send a file we are setting the Content-Type: application/pdf header
* only when an endpoint has the name start we setting Content-Length: 0 this should be refactored to some better code. Maybe when no data is set and now file is set? and on POST and PUT methodes?

https://github.com/Evidos/signhost-phpdemoclient/issues/16

**Comment by steffjenl** [comment]
`

            if (($method == 'PUT' || $method == 'POST') && empty($data) && empty($filePath)) {
                $headers[] = 'Content-Length: 0';
            }
`
Maybe this?

**Comment by jstolp** [comment]
Tested v1.3.10 with curl 7.68.0 (x86_64-redhat-linux-gnu) 
I get a 411 on Start Transaction.

**Comment by jstolp** [comment]
NOTE: v1.3.7 works with curl 7.68.0 (x86_64-redhat-linux-gnu)
